name: Deploy Firebase (Functions + Hosting)

on:
  push:
    branches: [ main ]
    paths:
      - 'functions/**'
      - 'src/**'
      - 'index.html'
      - 'vite.config.ts'
      - 'package.json'
      - 'tsconfig.json'
      - 'firebase.json'
      - '.firebaserc'

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          create_credentials_file: true
          export_environment_variables: true

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 476.0.0'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Prepare Python Functions environment
        run: |
          python -m venv functions/venv
          . functions/venv/bin/activate
          pip install --upgrade pip
          pip install -r functions/requirements.txt

      - name: Build Frontend
        run: |
          npm ci
          npm run build

      - name: Deploy Functions
        run: firebase deploy --only functions --project redditsearchtool

      - name: Deploy Hosting
        run: firebase deploy --only hosting --project redditsearchtool