name: (Deprecated) Deploy Firebase Functions

# Deprecated: use .github/workflows/deploy.yml instead.
on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy-functions:
    if: false  # Disabled in favor of unified workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          create_credentials_file: true
          export_environment_variables: true

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 476.0.0'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Verify Auth
        run: |
          gcloud auth list || true
          gcloud config list || true

      - name: Deploy Functions
        run: firebase deploy --only functions --project redditsearchtool
